"""test-generation-pipeline entrypoint.

AST-based pytest skeleton generator. Extracts functions/classes,
produces parametrised tests + edge-case stubs. Pure Python.
"""

from __future__ import annotations

import ast
import inspect
from pathlib import Path
from typing import Any


_CODE_TEMPLATE = '''\
"""Auto-generated tests for {module_name}.

Generated by test-generation-pipeline.
Fill in assertions and remove TODO stubs as needed.
"""

from __future__ import annotations

import pytest
{import_line}


{body}
'''


def _get_type_hint(param: ast.arg) -> str:
    """Return a string type hint if present, else 'Any'."""
    if param.annotation is None:
        return "Any"
    return ast.unparse(param.annotation)


def _default_value_for_type(type_hint: str) -> str:
    """Produce a reasonable literal for a type hint."""
    mapping = {
        "int": "0",
        "str": '"hello"',
        "float": "0.0",
        "bool": "True",
        "list": "[]",
        "dict": "{}",
        "Any": "None",
    }
    for key, val in mapping.items():
        if key in type_hint:
            return val
    return "None"


def _make_test_cases(func_name: str, args: list[ast.arg]) -> list[dict[str, str]]:
    """Generate 2–3 basic test case dicts for a function."""
    if not args:
        return [{"desc": f"basic call", "args": "", "expected": "None"}]

    arg_parts: list[str] = []
    for a in args:
        hint = _get_type_hint(a)
        val = _default_value_for_type(hint)
        arg_parts.append(f"{a.arg}={val}")

    cases = [
        {
            "desc": f"happy path",
            "args": ", ".join(arg_parts),
            "expected": "None  # TODO: set expected result",
        },
    ]

    # Edge: zero-like values
    edge_parts = []
    for a in args:
        hint = _get_type_hint(a)
        if "int" in hint:
            edge_parts.append(f"{a.arg}=0")
        elif "str" in hint:
            edge_parts.append(f'{a.arg}=""')
        elif "float" in hint:
            edge_parts.append(f"{a.arg}=0.0")
        elif "list" in hint:
            edge_parts.append(f"{a.arg}=[]")
        else:
            edge_parts.append(f"{a.arg}=None")
    cases.append({
        "desc": f"zero/empty input",
        "args": ", ".join(edge_parts),
        "expected": "None  # TODO: set expected result",
    })

    return cases


def _generate_function_test(func: ast.FunctionDef | ast.AsyncFunctionDef, module_name: str) -> str:
    """Generate test skeleton for a single function."""
    name = func.name
    if name.startswith("_"):
        return ""

    args = [a for a in func.args.args if a.arg not in ("self", "cls")]
    if func.args.vararg or func.args.kwarg:
        args = []  # skip *args/**kwargs functions for simplicity

    cases = _make_test_cases(name, args)
    lines: list[str] = []

    # One test per case
    for i, case in enumerate(cases):
        test_name = f"test_{name}_case_{i + 1}"
        lines.append(f"def {test_name}():")
        lines.append(f'    """{case["desc"]} for {name}."""')
        call_args = case["args"]
        if call_args:
            lines.append(f"    result = {module_name}.{name}({call_args})")
        else:
            lines.append(f"    result = {module_name}.{name}()")
        lines.append(f"    assert result == {case['expected']}")
        lines.append("")

    # Edge-case TODO stub
    lines.append(f"def test_{name}_edge_cases():")
    lines.append(f'    """Edge cases for {name} — fill in before merging."""')
    lines.append("    # TODO: overflow, NaN, unicode, large input, negative values")
    lines.append("    pass")
    lines.append("")

    return "\n".join(lines)


def _generate_class_tests(cls: ast.ClassDef, module_name: str) -> str:
    """Generate test skeletons for public methods of a class."""
    lines: list[str] = []
    methods = [
        node for node in cls.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and not node.name.startswith("_")
    ]
    if not methods:
        return ""

    lines.append(f"class Test{cls.name}:")
    lines.append(f'    """Tests for {cls.name}."""')
    lines.append("")

    for method in methods:
        args = [a for a in method.args.args if a.arg not in ("self", "cls")]
        cases = _make_test_cases(method.name, args)
        for i, case in enumerate(cases):
            lines.append(f"    def test_{method.name}_case_{i + 1}(self):")
            lines.append(f'        """{case["desc"]} for {method.name}."""')
            call_args = case["args"]
            init = f"obj = {module_name}.{cls.name}()"
            lines.append(f"        {init}")
            if call_args:
                lines.append(f"        result = obj.{method.name}({call_args})")
            else:
                lines.append(f"        result = obj.{method.name}()")
            lines.append(f"        assert result == {case['expected']}")
            lines.append("")

        lines.append(f"    def test_{method.name}_edge_cases(self):")
        lines.append(f'        """Edge cases for {method.name}."""')
        lines.append("        # TODO: add edge cases")
        lines.append("        pass")
        lines.append("")

    return "\n".join(lines)


def _needs_tmp_path(tree: ast.AST) -> bool:
    """Heuristic: does the module touch filesystem or env vars?"""
    for node in ast.walk(tree):
        if isinstance(node, ast.Name) and node.id in ("open", "Path", "os", "tempfile"):
            return True
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
            if node.value.id in ("os", "pathlib", "tempfile", "json"):
                return True
    return False


def _needs_monkeypatch(tree: ast.AST) -> bool:
    """Heuristic: does the module read env vars or external state?"""
    for node in ast.walk(tree):
        if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name):
            if node.value.id == "os" and node.attr in ("environ", "getenv"):
                return True
    return False


async def run_openagent_skill(payload: dict[str, Any]) -> dict[str, Any]:
    """Execute the test generation pipeline."""
    target_path = payload.get("target_path")
    output_path = payload.get("output_path")
    style = payload.get("style", "pytest")

    if not target_path:
        raise ValueError("test-generation-pipeline: payload must include 'target_path'")
    if not output_path:
        raise ValueError("test-generation-pipeline: payload must include 'output_path'")
    if style not in ("pytest", "unittest"):
        raise ValueError(f"test-generation-pipeline: invalid style '{style}'")

    target = Path(target_path)
    if not target.exists():
        raise FileNotFoundError(f"target_path does not exist: {target_path}")

    source = target.read_text(encoding="utf-8", errors="replace")
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        raise ValueError(f"Failed to parse {target_path}: {exc}") from exc

    module_name = target.stem
    import_line = f"import {module_name}"

    functions_tested: list[str] = []
    test_blocks: list[str] = []

    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                block = _generate_function_test(node, module_name)
                if block:
                    functions_tested.append(node.name)
                    test_blocks.append(block)
        elif isinstance(node, ast.ClassDef):
            block = _generate_class_tests(node, module_name)
            if block:
                functions_tested.append(node.name)
                test_blocks.append(block)

    body = "\n".join(test_blocks)
    if not body.strip():
        body = "# No public functions or classes found to test.\n"

    content = _CODE_TEMPLATE.format(
        module_name=module_name,
        import_line=import_line,
        body=body,
    )

    output_p = Path(output_path)
    output_p.parent.mkdir(parents=True, exist_ok=True)
    output_p.write_text(content, encoding="utf-8")

    fixture_hints: list[str] = []
    if _needs_tmp_path(tree):
        fixture_hints.append("tmp_path")
    if _needs_monkeypatch(tree):
        fixture_hints.append("monkeypatch")

    test_count = sum(1 for line in content.splitlines() if line.strip().startswith("def test_"))

    return {
        "test_path": str(output_p),
        "functions_tested": functions_tested,
        "test_count": test_count,
        "fixture_hints": fixture_hints,
        "notes": "Edge cases marked with # TODO — fill in before merging.",
    }
